/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once

/* RGB */
#define RGB_DI_PIN D2
#define RGBLED_NUM 16
#define RGB_MATRIX_LED_COUNT RGBLED_NUM
#define DRIVER_LED_TOTAL RGBLED_NUM
#define RGBLIGHT_HUE_STEP 5
#define RGB_MATRIX_KEYPRESSES

#define VIAL_KEYBOARD_UID {0x43, 0x1C, 0x0B, 0xD2, 0x2A, 0x50, 0x00, 0x48}
#define DYNAMIC_KEYMAP_LAYER_COUNT 2