#pragma once

#define VIAL_KEYBOARD_UID {0x3B, 0x6B, 0xA0, 0x29, 0x80, 0x56, 0xED, 0xD1}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define BACKLIGHT_PIN B5
#define BACKLIGHT_BREATHING

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define TAPPING_TERM 180
