GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
OLED_ENABLE = yes
ENCODER_MAP_ENABLE 	= yes

VIA_ENABLE = yes

# OLED WIDGETS

# WPM_ENABLE = no
# KEYCOUNT_ENABLE = yes
# KEYLOG_ENABLE = no
# KEYLOG_DEBUG = no